[gui]
last_procedure = "HighPowerPulseTest"

[window]
geometry = "AdnQywADAAAAAAHMAAAAeAAABbMAAAOIAAABzAAAAHgAAAWzAAADiAAAAAAAAAAAB4AAAAHMAAAAeAAABbMAAAOI"
state = "AAAA/wAAAAD9AAAAAQAAAAAAAAGeAAADEfwCAAAAAfsAAAAgAEkAbgBwAHUAdABfAFAAYQByAGEAbQBlAHQAZQByAHMBAAAAAAAAAxEAAAKKAP///wAAAkYAAAMRAAAABAAAAAQAAAAIAAAACPwAAAAA"

[directories]
Random_Number_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\rSCT\\Python Software\\data\\Random"
High_Power_Pulse_Test = "./data"
Double_Pulse_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\HPPT2\\Python Software\\data\\DPT"

[docks]
Random_Number_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [163, 163]}], \"float\": []}"
High_Power_Pulse_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [163, 163]}], \"float\": []}"
Double_Pulse_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [158, 175]}], \"float\": []}"

[gui.enabled.HighPowerPulseTest]
aps_controller = true
keithley_smu = true
nge103_psu = true
hmc8043_psu = false
keysight_oscilloscope = true

[gui.enabled.RandomProcedure]

[gui.connections.RandomProcedure]

[gui.connections.DoublePulseTest.aps_controller]
connection = "COM5"

[gui.connections.DoublePulseTest.hmc8043_psu]
connection = ""

[gui.connections.DoublePulseTest.keysight_oscilloscope]
connection = "USB0::0x2A8D::0x904A::MY58150189::INSTR"

[gui.connections.HighPowerPulseTest.aps_controller]
connection = "COM8"

[gui.connections.HighPowerPulseTest.keithley_smu]
connection = "GPIB::24"

[gui.connections.HighPowerPulseTest.nge103_psu]
connection = ""

[gui.connections.HighPowerPulseTest.hmc8043_psu]
connection = ""

[gui.connections.HighPowerPulseTest.keysight_oscilloscope]
connection = "USB0::0x2A8D::0x904A::MY58150189::INST"
