[gui]
last_procedure = "DoublePulseTest"

[window]
geometry = "AdnQywADAAAAAAHMAAAAeAAABbMAAAOXAAABzAAAAHgAAAWzAAADlwAAAAAAAAAAB4AAAAHMAAAAeAAABbMAAAOX"
state = "AAAA/wAAAAD9AAAAAQAAAAAAAAEeAAADIPwCAAAAAfsAAAAgAEkAbgBwAHUAdABfAFAAYQByAGEAbQBlAHQAZQByAHMBAAAAAAAAAyAAAAL6AP///wAAAsYAAAMgAAAABAAAAAQAAAAIAAAACPwAAAAA"

[directories]
Random_Number_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\rSCT\\Python Software\\data\\Random"
High_Power_Pulse_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\rSCT\\Python Software\\data\\HPPT"
Double_Pulse_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\HPPT2\\Python Software\\data\\DPT"

[docks]
Random_Number_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [249, 249]}], \"float\": []}"
High_Power_Pulse_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [461, 459]}], \"float\": []}"
Double_Pulse_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [167, 166]}], \"float\": []}"

[gui.connections.DoublePulseTest.aps_controller]
connection = "COM5"
