[gui]
last_procedure = "DoublePulseTest"

[window]
geometry = "AdnQywADAAAAAAAAAAAAIgAADv8AAAgnAAAFjAAAAoQAAAlzAAAGcgAAAAACAAAADwAAAAAAAAAAIgAADv8AAAgn"
state = "AAAA/wAAAAD9AAAAAQAAAAAAAAGeAAAIBvwCAAAAAfsAAAAgAEkAbgBwAHUAdABfAFAAYQByAGEAbQBlAHQAZQByAHMBAAAAAAAACAYAAAPvAP///wAADVwAAAgGAAAABAAAAAQAAAAIAAAACPwAAAAA"

[directories]
Random_Number_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\rSCT\\Python Software\\data\\Random"
High_Power_Pulse_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\rSCT\\Python Software\\data\\HPPT"
Double_Pulse_Test = "e:\\Projekte\\Ziemann Engineering\\Projekte\\HPPT2\\Python Software\\data\\DPT"

[docks]
Random_Number_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [249, 249]}], \"float\": []}"
High_Power_Pulse_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [461, 459]}], \"float\": []}"
Double_Pulse_Test = "json:{\"main\": [\"vertical\", [[\"dock\", \"Dock 1\", {}], [\"dock\", \"Dock 2\", {}]], {\"sizes\": [436, 484]}], \"float\": []}"

[gui.connections.DoublePulseTest.aps_controller]
connection = "ASRL7::INSTR"

[gui.connections.DoublePulseTest.nge100_psu]
connection = "ASRL1::INSTR"

[gui.connections.DoublePulseTest.keysight_oscilloscope]
connection = "USB0::0x2A8D::0x904A::MY58150189::INSTR"
